const $=s=>document.querySelector(s),EDGE='https://hmsldwpcaupanooestfr.supabase.co/functions/v1/pricewatcher-api',HISTORY_EDGE='https://hmsldwpcaupanooestfr.supabase.co/functions/v1/pricewatcher-history',CHECK_EDGE='https://hmsldwpcaupanooestfr.supabase.co/functions/v1/pricewatcher-check',AUTH='https://hmsldwpcaupanooestfr.supabase.co',KEY='sb_publishable_QCWt9V-_up-ePCszAB9S1A_k2-bPOQj';
let accessToken=localStorage.getItem('pw_access_token')||'',refreshToken=localStorage.getItem('pw_refresh_token')||'',monitor=null;
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>d?new Date(d).toLocaleString():'Never';
function saveAuth(d){if(d?.access_token){accessToken=d.access_token;localStorage.setItem('pw_access_token',accessToken)}if(d?.refresh_token){refreshToken=d.refresh_token;localStorage.setItem('pw_refresh_token',refreshToken)}}
async function refreshAuth(){if(!refreshToken)return false;try{const r=await fetch(`${AUTH}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});if(!r.ok)return false;saveAuth(await r.json());return true}catch{return false}}
async function call(url,payload,retry=true){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify({...payload,access_token:accessToken})}),d=await r.json().catch(()=>({}));if(r.status===401&&retry&&await refreshAuth())return call(url,payload,false);if(!r.ok){const e=new Error(d.error||'Request failed');e.status=r.status;throw e}return d}
const api=(action,payload={})=>call(EDGE,{action,...payload}),history=id=>call(HISTORY_EDGE,{id});
function money(p){if(p?.raw_price)return p.raw_price;if(p?.price)return p.price;if(p?.amount===0)return 'Free';if(p?.amount!=null){try{return new Intl.NumberFormat(undefined,{style:'currency',currency:p.currency||'USD',maximumFractionDigits:2}).format(Number(p.amount))}catch{return String(p.amount)}}return 'Custom'}
function interval(n){return({60:'Hourly',360:'Every 6 hours',720:'Every 12 hours',1440:'Daily',10080:'Weekly'})[Number(n)]||'Daily'}
function chart(snapshots){const byPlan=new Map();for(const s of snapshots||[])for(const p of s.pricing_structure?.plans||[]){if(p?.amount==null)continue;const name=String(p.name||'Plan').trim();if(!byPlan.has(name))byPlan.set(name,[]);byPlan.get(name).push({date:new Date(s.created_at),amount:Number(p.amount),currency:p.currency||'USD'})}const series=[...byPlan.entries()].map(([name,points])=>({name,points})).filter(x=>x.points.length);if(!series.length)return '<div class="detail-empty">No numeric plan prices have been captured yet. History will appear after future snapshots.</div>';const all=series.flatMap(s=>s.points),minT=Math.min(...all.map(p=>p.date.getTime())),maxT=Math.max(...all.map(p=>p.date.getTime())),maxV=Math.max(1,...all.map(p=>p.amount)),W=760,H=250,L=52,R=18,T=18,B=42,x=t=>L+(maxT===minT?(W-L-R)/2:(t-minT)/(maxT-minT)*(W-L-R)),y=v=>T+(H-T-B)-(v/maxV)*(H-T-B),grid=[0,.25,.5,.75,1].map(f=>`<line x1="${L}" y1="${y(maxV*f)}" x2="${W-R}" y2="${y(maxV*f)}" class="chart-grid"/><text x="${L-8}" y="${y(maxV*f)+4}" text-anchor="end" class="chart-axis">${esc(Math.round(maxV*f).toLocaleString())}</text>`).join(''),lines=series.map((s,i)=>{const hue=i*67%360,pts=s.points.map(p=>`${x(p.date.getTime()).toFixed(1)},${y(p.amount).toFixed(1)}`).join(' ');return `<polyline points="${pts}" class="chart-line" style="--series-h:${hue}"/>${s.points.map(p=>`<circle cx="${x(p.date.getTime()).toFixed(1)}" cy="${y(p.amount).toFixed(1)}" r="4" style="--series-h:${hue}"><title>${esc(s.name)} · ${esc(money(p))} · ${esc(p.date.toLocaleDateString())}</title></circle>`).join('')}`}).join(''),legend=series.map((s,i)=>`<span><i style="--series-h:${i*67%360}"></i>${esc(s.name)} <b>${esc(money(s.points.at(-1)))}</b></span>`).join('');return `<div class="price-history-chart"><div class="chart-scroll"><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Plan price history chart">${grid}${lines}<text x="${L}" y="${H-10}" class="chart-axis">${esc(new Date(minT).toLocaleDateString())}</text><text x="${W-R}" y="${H-10}" text-anchor="end" class="chart-axis">${esc(new Date(maxT).toLocaleDateString())}</text></svg></div><div class="chart-legend">${legend}</div></div>`}
function render(h){const status=monitor.is_active?monitor.last_status:'paused',plans=monitor.pricing_overview?.plans||[],changes=h.changes||[];document.title=`${monitor.name} · PlanSentry`;$('#competitor-name').textContent=monitor.name;$('#competitor-url').textContent=monitor.url;$('#competitor-url').href=monitor.url;$('#competitor-status').textContent=status;$('#competitor-status').className=`detail-status ${status}`;$('#pricing-captured').textContent=monitor.pricing_overview?.captured_at?`Captured ${new Date(monitor.pricing_overview.captured_at).toLocaleDateString()}`:'Latest snapshot';$('#detail-stats').innerHTML=`<div><b>${monitor.snapshot_count||0}</b><span>Snapshots</span></div><div><b>${monitor.change_count||0}</b><span>Changes detected</span></div><div><b>${monitor.unreviewed_count||0}</b><span>Unreviewed</span></div><div><b>${interval(monitor.check_interval_minutes)}</b><span>Check cadence</span></div>`;$('#current-pricing').innerHTML=plans.length?`<div class="plan-grid">${plans.map(p=>`<article><span>${esc(p.name||'Plan')}</span><b>${esc(money(p))}</b>${p.billing_period?`<small>${esc(p.billing_period)}</small>`:''}</article>`).join('')}</div>`:'<div class="detail-empty">No structured prices are available yet. Run a fresh check to try capturing this page’s plans.</div>';$('#price-history').innerHTML=chart(h.snapshots||[]);$('#recent-changes').innerHTML=changes.length?changes.slice(0,8).map(c=>`<article class="activity ${esc(c.severity||'low')}"><div><b>${esc(c.summary||'Pricing content changed')}</b><span>${fmt(c.created_at)}</span></div><span>${esc(c.change_type||'change')}</span></article>`).join(''):'<div class="detail-empty">No pricing changes recorded yet.</div>';const healthy=!monitor.consecutive_failures&&monitor.last_status!=='error';$('#monitor-health').innerHTML=`<div class="health-state ${healthy?'healthy':'warning'}"><i></i><div><b>${healthy?'Monitor healthy':'Needs attention'}</b><span>${monitor.consecutive_failures?`${monitor.consecutive_failures} consecutive failures`:'Latest crawl completed normally'}</span></div></div><dl><div><dt>Last checked</dt><dd>${esc(fmt(monitor.last_checked_at))}</dd></div><div><dt>Next scheduled</dt><dd>${monitor.is_active?esc(fmt(monitor.next_check_at)):'Paused'}</dd></div><div><dt>Last HTTP status</dt><dd>${esc(monitor.last_http_status?String(monitor.last_http_status):'—')}</dd></div><div><dt>Last success</dt><dd>${esc(fmt(monitor.last_success_at))}</dd></div></dl>${monitor.last_error?`<div class="detail-error">${esc(monitor.last_error)}</div>`:''}`;$('#notes').value=monitor.notes||'';updateCount()}
function updateCount(){$('#notes-count').textContent=`${$('#notes').value.length} / 2000`}
async function load(){const id=new URLSearchParams(location.search).get('id');if(!accessToken){$('#gate').hidden=false;return}if(!id){location.replace('/app');return}try{const [rows,h]=await Promise.all([api('list'),history(id)]);monitor=rows.find(x=>x.id===id);if(!monitor)throw new Error('Competitor not found');render(h);$('#detail-app').hidden=false}catch(e){if(e.status===401){$('#gate').hidden=false}else{$('#detail-app').hidden=false;$('#detail-message').textContent=e.message;$('#detail-message').className='error'}}}
$('#notes').addEventListener('input',updateCount);$('#save-notes').onclick=async()=>{const b=$('#save-notes');b.disabled=true;$('#detail-message').className='';$('#detail-message').textContent='Saving notes…';try{monitor=await api('update',{id:monitor.id,notes:$('#notes').value});$('#detail-message').textContent='Notes saved.'}catch(e){$('#detail-message').textContent=e.message;$('#detail-message').className='error'}finally{b.disabled=false}};$('#check-now').onclick=async()=>{const b=$('#check-now');b.disabled=true;$('#detail-message').className='';$('#detail-message').textContent='Checking pricing page…';try{await call(CHECK_EDGE,{action:'one',id:monitor.id});$('#detail-message').textContent='Check complete.';await load()}catch(e){$('#detail-message').textContent=e.message;$('#detail-message').className='error'}finally{b.disabled=false}};
load();
