const CREATE_EDGE='https://hmsldwpcaupanooestfr.supabase.co/functions/v1/pricewatcher-monitor-create';
async function createMonitorHardened(payload,retry=true){const r=await fetch(CREATE_EDGE,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify({...payload,access_token:accessToken})});const d=await r.json().catch(()=>({}));if(r.status===401&&retry&&await refreshAuth())return createMonitorHardened(payload,false);if(!r.ok){const e=new Error(d.error||'Unable to create monitor');e.status=r.status;throw e}return d}
const monitorForm=document.querySelector('#form'),progress=document.querySelector('#monitor-progress'),progressTitle=document.querySelector('#progress-title'),progressDetail=document.querySelector('#progress-detail');
function normalizePricingUrl(value){const trimmed=value.trim();if(!trimmed)return'';return /^[a-z][a-z\d+.-]*:\/\//i.test(trimmed)?trimmed:`https://${trimmed}`}
function setProgress(step,title,detail){if(!progress)return;progress.hidden=false;progress.dataset.step=String(step);progressTitle.textContent=title;progressDetail.textContent=detail}
function finishProgress(){if(progress){progress.hidden=true;progress.dataset.step='0'}}
function updateCadenceOptions(){const free=!accountInfo||String(accountInfo.plan||'free')==='free',select=$('#interval');if(!select)return;[...select.options].forEach(option=>{const paid=Number(option.value)<1440,base=option.textContent.split(' · ')[0];option.disabled=free&&paid;option.textContent=base+(free&&paid?' · Pro':'')});if(free&&Number(select.value)<1440)select.value='1440'}
const baseUpdateAccountUI=updateAccountUI;updateAccountUI=function(){baseUpdateAccountUI();updateCadenceOptions()};
$('#url')?.addEventListener('blur',event=>{const normalized=normalizePricingUrl(event.currentTarget.value);if(normalized)event.currentTarget.value=normalized});
if(monitorForm)monitorForm.onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button'),name=$('#name').value.trim(),url=normalizePricingUrl($('#url').value);$('#url').value=url;msg.textContent='';button.disabled=true;setProgress(1,'Validating pricing page…','Checking that the URL is safe and ready to monitor.');const timerOne=setTimeout(()=>setProgress(2,'Opening the pricing page…','PlanSentry is following safe redirects and reading public pricing content.'),900),timerTwo=setTimeout(()=>setProgress(3,'Building the first snapshot…','Extracting plans, prices, billing periods, limits, and packaging signals.'),2600);try{const d=await createMonitorHardened({name,url,check_interval_minutes:Number($('#interval').value)});clearTimeout(timerOne);clearTimeout(timerTwo);setProgress(4,d.warning?'Monitor created with a warning':'Monitor ready',d.warning?'The page was saved, but the first capture needs attention.':'Your baseline is saved and scheduled monitoring is active.');$('#name').value='';$('#url').value='';msg.textContent=d.warning?`Initial capture warning: ${d.warning}`:'First snapshot captured. Future pricing changes will appear in your dashboard.';await load(true);setTimeout(finishProgress,2200)}catch(e){clearTimeout(timerOne);clearTimeout(timerTwo);finishProgress();msg.textContent=e.message;if(e.status===402)msg.innerHTML=`${esc(e.message)} <a href="/#pricing">View plans</a>`}finally{button.disabled=false}};
updateCadenceOptions();
