const EDGE='https://hmsldwpcaupanooestfr.supabase.co/functions/v1/pricewatcher-api',AUTH='https://hmsldwpcaupanooestfr.supabase.co',KEY='sb_publishable_QCWt9V-_up-ePCszAB9S1A_k2-bPOQj';
let accessToken=localStorage.getItem('pw_access_token')||'',refreshToken=localStorage.getItem('pw_refresh_token')||'',rows=[];
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function refreshAuth(){if(!refreshToken)return false;const r=await fetch(`${AUTH}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});if(!r.ok)return false;const d=await r.json();accessToken=d.access_token;refreshToken=d.refresh_token||refreshToken;localStorage.setItem('pw_access_token',accessToken);localStorage.setItem('pw_refresh_token',refreshToken);return true}
async function api(action,payload={},retry=true){const r=await fetch(EDGE,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify({action,...payload,access_token:accessToken})});const d=await r.json().catch(()=>({}));if(r.status===401&&retry&&await refreshAuth())return api(action,payload,false);if(!r.ok)throw new Error(d.error||'Request failed');return d}
function displayPrice(p){if(p?.raw_price)return p.raw_price;if(p?.amount===0)return'Free';if(p?.amount!=null){const sym=p.currency==='EUR'?'€':p.currency==='GBP'?'£':'$';return`${sym}${p.amount}${p.interval?`/${p.interval==='month'?'mo':p.interval}`:''}`}return'Custom'}
function planKeys(data){const counts=new Map();data.forEach(m=>(m.pricing_overview?.plans||[]).forEach(p=>{const n=String(p.name||'Plan').trim();if(n)counts.set(n,(counts.get(n)||0)+1)}));return[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,12).map(x=>x[0])}
function insights(data){const paid=[];let freeCount=0,custom=0;data.forEach(m=>(m.pricing_overview?.plans||[]).forEach(p=>{if(Number(p.amount)===0)freeCount++;else if(p.amount!=null&&Number(p.amount)>0)paid.push(Number(p.amount));else if(String(p.raw_price||'').toLowerCase().includes('custom'))custom++}));paid.sort((a,b)=>a-b);const median=paid.length?paid[Math.floor(paid.length/2)]:null;$('#matrix-insights').innerHTML=`<div class="matrix-insight"><span>Competitors tracked</span><b>${data.length}</b><p>Included in the current comparison.</p></div><div class="matrix-insight"><span>Median paid price</span><b>${median==null?'—':`$${median}`}</b><p>Across numeric structured plan prices.</p></div><div class="matrix-insight"><span>Free tiers detected</span><b>${freeCount}</b><p>${custom} custom-priced plan${custom===1?'':'s'} also detected.</p></div>`}
function labels(m){const parts=[];if(m.group_name)parts.push(`<span class="group">${esc(m.group_name)}</span>`);(m.tags||[]).forEach(x=>parts.push(`<span>#${esc(x)}</span>`));return parts.length?`<div class="matrix-labels">${parts.join('')}</div>`:''}
function populateGroups(){const select=$('#matrix-group'),current=select.value||'all',groups=[...new Set(rows.map(x=>x.group_name).filter(Boolean))].sort((a,b)=>a.localeCompare(b));select.innerHTML='<option value="all">All groups</option><option value="ungrouped">Ungrouped</option>'+groups.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');select.value=[...select.options].some(x=>x.value===current)?current:'all'}
function render(){const q=$('#matrix-search').value.trim().toLowerCase(),group=$('#matrix-group').value;const data=rows.filter(m=>{if(group!=='all'&&(group==='ungrouped'?!!m.group_name:m.group_name!==group))return false;const hay=[m.name,m.url,m.group_name,...(m.tags||[])].join(' ').toLowerCase();return!q||hay.includes(q)||(m.pricing_overview?.plans||[]).some(p=>String(p.name||'').toLowerCase().includes(q)||String(displayPrice(p)).toLowerCase().includes(q))});const keys=planKeys(data);if(!data.length){$('#matrix').innerHTML='<div class="matrix-empty">No competitors match these filters.</div>';insights([]);return}const head=keys.map(k=>`<th>${esc(k)}</th>`).join(''),body=data.map(m=>{const map=new Map((m.pricing_overview?.plans||[]).map(p=>[String(p.name||'Plan').trim().toLowerCase(),p]));return`<tr><td><span class="competitor-name">${esc(m.name)}</span><a class="competitor-url" href="${esc(m.url)}" target="_blank" rel="noopener">${esc(m.url)}</a>${labels(m)}</td>${keys.map(k=>{const p=map.get(k.toLowerCase());return p?`<td><div class="matrix-price"><b>${esc(displayPrice(p))}</b><span>${esc(p.interval||p.currency||'')}</span></div></td>`:'<td class="matrix-missing">—</td>'}).join('')}</tr>`}).join('');$('#matrix').innerHTML=`<div class="matrix-scroll"><table class="matrix-table"><thead><tr><th>Competitor</th>${head}</tr></thead><tbody>${body}</tbody></table></div>`;insights(data)}
async function load(){if(!accessToken){location.href='/account.html';return}$('#matrix-status').textContent='Loading…';try{rows=await api('list');populateGroups();render();$('#matrix-status').textContent=`Updated ${new Date().toLocaleTimeString()}`}catch(e){$('#matrix-status').textContent=e.message}}
$('#matrix-search').addEventListener('input',render);$('#matrix-group').addEventListener('change',render);$('#matrix-refresh').onclick=load;load();
