import crypto from 'node:crypto';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;
const headers=()=>{if(!url||!key)throw new Error('Supabase env vars missing');return{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'}};
export async function select(path){const r=await fetch(`${url}/rest/v1/${path}`,{headers:headers()});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function insert(table,row){const r=await fetch(`${url}/rest/v1/${table}`,{method:'POST',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify(row)});if(!r.ok)throw new Error(await r.text());return (await r.json())[0]}
export async function update(table,q,row){const r=await fetch(`${url}/rest/v1/${table}?${q}`,{method:'PATCH',headers:headers(),body:JSON.stringify(row)});if(!r.ok)throw new Error(await r.text())}
const norm=s=>String(s).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#39;/g,"'").replace(/&quot;/gi,'"').replace(/\s+/g,' ').trim();
export async function scrape(target){const u=new URL(target);if(!['http:','https:'].includes(u.protocol))throw new Error('Only http/https URLs allowed');const r=await fetch(target,{redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (compatible; PriceWatcherBot/0.1)'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`Fetch failed: ${r.status}`);const html=await r.text();const title=norm((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||u.hostname);const body=norm(html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<svg[\s\S]*?<\/svg>/gi,' ').replace(/<[^>]+>/g,'\n'));const chunks=body.split(/(?<=[.!?])\s+|\n+/).map(norm).filter(Boolean),pat=/(\$|€|£|usd|eur|gbp|\/mo|\/month|\/yr|\/year|monthly|annually|per month|per year|free|starter|pro|business|enterprise|pricing|plan)/i,hits=chunks.filter(x=>pat.test(x)),pricing=(hits.length?hits:chunks).slice(0,250).join('\n'),hash=crypto.createHash('sha256').update(pricing).digest('hex');return{title,pricing,hash}}
export function diff(a,b){const lines=s=>s.split(/\n|(?<=[.!?])\s+/).map(norm).filter(Boolean),A=new Set(lines(a)),B=new Set(lines(b));return{added:[...B].filter(x=>!A.has(x)).slice(0,30),removed:[...A].filter(x=>!B.has(x)).slice(0,30)}}
export async function runCheck(id){const m=(await select(`monitors?id=eq.${encodeURIComponent(id)}&select=*`))[0];if(!m)throw new Error('Monitor not found');const s=await scrape(m.url),old=(await select(`snapshots?monitor_id=eq.${encodeURIComponent(id)}&select=*&order=created_at.desc&limit=1`))[0];let change=null;if(old&&old.content_hash!==s.hash){const d=diff(old.pricing_text,s.pricing);change=await insert('changes',{monitor_id:id,previous_snapshot_id:old.id,added_lines:d.added,removed_lines:d.removed});await alert(m,d)}await insert('snapshots',{monitor_id:id,page_title:s.title,content_hash:s.hash,pricing_text:s.pricing});await update('monitors',`id=eq.${encodeURIComponent(id)}`,{last_checked_at:new Date().toISOString(),last_status:'ok'});return{changed:!!change,change,title:s.title}}
async function alert(m,d){const api=process.env.RESEND_API_KEY,to=process.env.ALERT_TO_EMAIL,from=process.env.ALERT_FROM_EMAIL;if(!api||!to||!from)return;const esc=x=>String(x).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${api}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject:`Pricing change detected: ${m.name}`,html:`<h2>${esc(m.name)} changed</h2><p>${esc(m.url)}</p><h3>Added</h3>${d.added.map(x=>`<p>+ ${esc(x)}</p>`).join('')}<h3>Removed</h3>${d.removed.map(x=>`<p>− ${esc(x)}</p>`).join('')}`})})}
