import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get('SUPABASE_URL')!,K=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const H={apikey:K,Authorization:`Bearer ${K}`,'Content-Type':'application/json'};
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,authorization,apikey'};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json',...CORS}});
const norm=(s:string)=>String(s).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#39;/g,"'").replace(/&quot;/gi,'"').replace(/\s+/g,' ').trim();
async function sel(p:string){const r=await fetch(`${U}/rest/v1/${p}`,{headers:H});if(!r.ok)throw new Error(await r.text());return r.json()}
async function ins(t:string,o:unknown){const r=await fetch(`${U}/rest/v1/${t}`,{method:'POST',headers:{...H,Prefer:'return=representation'},body:JSON.stringify(o)});if(!r.ok)throw new Error(await r.text());return(await r.json())[0]}
async function upd(t:string,q:string,o:unknown){const r=await fetch(`${U}/rest/v1/${t}?${q}`,{method:'PATCH',headers:{...H,Prefer:'return=representation'},body:JSON.stringify(o)});if(!r.ok)throw new Error(await r.text());const a=await r.json();return a[0]}
async function del(t:string,q:string){const r=await fetch(`${U}/rest/v1/${t}?${q}`,{method:'DELETE',headers:H});if(!r.ok)throw new Error(await r.text())}
async function sha(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function blocked(h:string){h=h.toLowerCase();return h==='localhost'||h==='0.0.0.0'||h==='127.0.0.1'||h==='::1'||h.endsWith('.local')||h.endsWith('.internal')||h==='metadata.google.internal'||/^10\./.test(h)||/^192\.168\./.test(h)||/^172\.(1[6-9]|2\d|3[01])\./.test(h)||/^169\.254\./.test(h)||/^100\.(6[4-9]|[7-9]\d|1[01]\d|12[0-7])\./.test(h)}
function safe(s:string){const u=new URL(s),h=u.hostname.toLowerCase();if(!['http:','https:'].includes(u.protocol)||blocked(h))throw new Error('Private/internal URLs are not allowed');return u}
async function fetchSafe(target:string){let current=safe(target);for(let i=0;i<6;i++){const r=await fetch(current,{redirect:'manual',headers:{'user-agent':'Mozilla/5.0 (compatible; PlanSentryBot/0.5)'}});if(r.status>=300&&r.status<400){const loc=r.headers.get('location');if(!loc)throw new Error('Invalid redirect');current=safe(new URL(loc,current).toString());continue}if(!r.ok)throw new Error(`Fetch failed: ${r.status}`);return{r,u:current}}throw new Error('Too many redirects')}
async function scrape(target:string){const{r,u}=await fetchSafe(target);const html=(await r.text()).slice(0,2500000),title=norm((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||u.hostname),body=norm(html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<svg[\s\S]*?<\/svg>/gi,' ').replace(/<[^>]+>/g,'\n')),chunks=body.split(/(?<=[.!?])\s+|\n+/).map(norm).filter(Boolean),pat=/(\$|€|£|usd|eur|gbp|\/mo|\/month|\/yr|\/year|monthly|annually|per month|per year|free|starter|pro|business|enterprise|pricing|plan|seat|user|credit|usage|limit)/i,hits=chunks.filter(x=>pat.test(x)),pricing=(hits.length?hits:chunks).slice(0,300).join('\n');if(!pricing)throw new Error('No readable pricing content found');return{title,pricing,hash:await sha(pricing)}}
function diff(a:string,b:string){const ls=(s:string)=>s.split(/\n|(?<=[.!?])\s+/).map(norm).filter(Boolean),A=new Set(ls(a)),B=new Set(ls(b));return{added:[...B].filter(x=>!A.has(x)).slice(0,50),removed:[...A].filter(x=>!B.has(x)).slice(0,50)}}
async function sendWebhook(m:any,change:any,title:string,test=false){if(!m.webhook_url||(!m.webhook_enabled&&!test))return{sent:false};const u=safe(String(m.webhook_url));const text=test?`PlanSentry test alert for ${m.name}`:`PlanSentry detected a pricing change for ${m.name}`;const payload={text,content:text,event:test?'pricewatcher.test':'pricewatcher.pricing_change',monitor:{id:m.id,name:m.name,url:m.url},page_title:title||null,change:change||null,detected_at:new Date().toISOString()};const r=await fetch(u,{method:'POST',redirect:'manual',headers:{'Content-Type':'application/json','User-Agent':'PlanSentryBot/0.5'},body:JSON.stringify(payload)});if(r.status>=300&&r.status<400)throw new Error('Webhook redirects are not allowed');if(!r.ok)throw new Error(`Webhook failed: ${r.status}`);await upd('monitors',`id=eq.${encodeURIComponent(m.id)}`,{last_notification_at:new Date().toISOString()});return{sent:true,status:r.status}}
async function authUser(raw:string){if(!raw)return null;const r=await fetch(`${U}/auth/v1/user`,{headers:{apikey:K,Authorization:`Bearer ${raw}`}});if(!r.ok)return null;return await r.json()}
async function context(body:any){const access=String(body.access_token||'');if(!access)return null;const user=await authUser(access);return user?.id?{mode:'user',user,access}:null}
const ownerQ=(ctx:any)=>`owner_id=eq.${encodeURIComponent(ctx.user.id)}`;
async function account(ctx:any){let a=(await sel(`user_accounts?user_id=eq.${encodeURIComponent(ctx.user.id)}&select=*&limit=1`))[0];if(!a)a=await ins('user_accounts',{user_id:ctx.user.id,email:ctx.user.email||null});else if(ctx.user.email&&a.email!==ctx.user.email)a=await upd('user_accounts',`user_id=eq.${encodeURIComponent(ctx.user.id)}`,{email:ctx.user.email});const limit=a.plan==='pro'||a.plan==='business'?null:a.plan==='plus'?25:3;const count=(await sel(`monitors?owner_id=eq.${encodeURIComponent(ctx.user.id)}&select=id`)).length;return{...a,limit,monitor_count:count}}
async function ownedMonitor(ctx:any,id:string){return (await sel(`monitors?id=eq.${encodeURIComponent(id)}&${ownerQ(ctx)}&select=*`))[0]}
async function check(ctx:any,id:string){const m=await ownedMonitor(ctx,id);if(!m)throw new Error('Monitor not found');if(!m.is_active)throw new Error('Monitor is paused');try{const s=await scrape(m.url),old=(await sel(`snapshots?monitor_id=eq.${encodeURIComponent(id)}&select=*&order=created_at.desc&limit=1`))[0];let change=null,notification=null;if(old&&old.content_hash!==s.hash){const d=diff(old.pricing_text,s.pricing);change=await ins('changes',{monitor_id:id,previous_snapshot_id:old.id,added_lines:d.added,removed_lines:d.removed});try{notification=await sendWebhook(m,change,s.title)}catch(e){notification={sent:false,error:e instanceof Error?e.message:String(e)}}}await ins('snapshots',{monitor_id:id,page_title:s.title,content_hash:s.hash,pricing_text:s.pricing});await upd('monitors',`id=eq.${encodeURIComponent(id)}`,{last_checked_at:new Date().toISOString(),last_status:'ok',last_error:null,updated_at:new Date().toISOString()});return{changed:!!change,change,title:s.title,notification}}catch(e){const message=e instanceof Error?e.message:String(e);await upd('monitors',`id=eq.${encodeURIComponent(id)}`,{last_checked_at:new Date().toISOString(),last_status:'error',last_error:message,updated_at:new Date().toISOString()});throw e}}
async function rateLimit(key:string,limit:number,windowMinutes:number){const now=Date.now(),rows=await sel(`beta_rate_limits?key=eq.${encodeURIComponent(key)}&select=*`),row=rows[0];if(!row){await ins('beta_rate_limits',{key,window_start:new Date(now).toISOString(),count:1});return true}const start=new Date(row.window_start).getTime();if(now-start>=windowMinutes*60000){await upd('beta_rate_limits',`key=eq.${encodeURIComponent(key)}`,{window_start:new Date(now).toISOString(),count:1});return true}if(Number(row.count)>=limit)return false;await upd('beta_rate_limits',`key=eq.${encodeURIComponent(key)}`,{count:Number(row.count)+1});return true}
const allowedIntervals=new Set([60,360,720,1440,10080]);const nextAt=(m:any)=>!m.is_active||!m.last_checked_at?null:new Date(new Date(m.last_checked_at).getTime()+Number(m.check_interval_minutes||1440)*60000).toISOString();
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});try{const body=await req.json().catch(()=>({}));const ctx=await context(body);if(!ctx)return json({error:'Authentication required'},401);
if(body.action==='account')return json(await account(ctx));
if(body.action==='list'){const m=await sel(`monitors?${ownerQ(ctx)}&select=*&order=created_at.desc`),ids=m.map((x:any)=>x.id);if(!ids.length)return json([]);const ors=ids.map((id:string)=>`monitor_id.eq.${id}`).join(','),c=await sel(`changes?or=(${ors})&select=*&order=created_at.desc&limit=500`),s=await sel(`snapshots?or=(${ors})&select=id,monitor_id,created_at,pricing_text,pricing_structure&order=created_at.desc&limit=2000`);return json(m.map((x:any)=>{const ch=c.filter((y:any)=>y.monitor_id===x.id),ms=s.filter((y:any)=>y.monitor_id===x.id),latest=ms[0];return{...x,next_check_at:nextAt(x),changes:ch.slice(0,10),change_count:ch.length,unreviewed_count:ch.filter((y:any)=>!y.reviewed_at).length,snapshot_count:ms.length,pricing_overview:{...(latest?.pricing_structure||{plans:[]}),captured_at:latest?.created_at||null}}}))}
if(body.action==='create'){if(!body.name||!body.url)return json({error:'Name and URL required'},400);const a=await account(ctx);if(a.limit!==null&&a.monitor_count>=a.limit)return json({error:`${a.plan[0].toUpperCase()+a.plan.slice(1)} plan allows ${a.limit} monitors. Upgrade to add more.`},402);const name=String(body.name).trim(),url=String(body.url).trim();safe(url);const interval=Number(body.check_interval_minutes||1440);if(!allowedIntervals.has(interval))return json({error:'Invalid check interval'},400);if(a.plan==='free'&&interval<1440)return json({error:'Free monitors can run daily or weekly. Upgrade for faster checks.'},402);let webhook_url=null,webhook_enabled=false;if(body.webhook_url){webhook_url=String(body.webhook_url).trim();safe(webhook_url);webhook_enabled=!!body.webhook_enabled}try{const row=await ins('monitors',{name,url,check_interval_minutes:interval,is_active:true,webhook_url,webhook_enabled,owner_id:ctx.user.id});try{await check(ctx,row.id)}catch(e){return json({...row,warning:e instanceof Error?e.message:String(e)},201)}return json(row,201)}catch(e){const msg=e instanceof Error?e.message:String(e);if(msg.includes('monitors_beta_url_unique_idx')||msg.includes('monitors_owner_url_unique_idx'))return json({error:'That pricing URL is already being monitored.'},409);throw e}}
if(body.action==='check'){if(!body.id)return json({error:'Missing id'},400);const key=ctx.user.id;if(!await rateLimit(`check:${await sha(key)}`,30,60))return json({error:'Manual check limit reached. Try again later.'},429);return json(await check(ctx,String(body.id)))}
if(body.action==='check_all'){const ms=(await sel(`monitors?${ownerQ(ctx)}&is_active=eq.true&select=id,name&order=created_at.asc`)).slice(0,100),results=[];for(const m of ms){try{const r=await check(ctx,m.id);results.push({id:m.id,name:m.name,ok:true,changed:r.changed})}catch(e){results.push({id:m.id,name:m.name,ok:false,error:e instanceof Error?e.message:String(e)})}}return json({checked:results.length,changed:results.filter((x:any)=>x.changed).length,errors:results.filter((x:any)=>!x.ok).length,results})}
if(body.action==='update'){if(!body.id)return json({error:'Missing id'},400);const m=await ownedMonitor(ctx,String(body.id));if(!m)return json({error:'Monitor not found'},404);const patch:any={updated_at:new Date().toISOString()};if(typeof body.name==='string'&&body.name.trim())patch.name=body.name.trim();if(typeof body.url==='string'&&body.url.trim()){safe(body.url.trim());patch.url=body.url.trim()}if(typeof body.is_active==='boolean')patch.is_active=body.is_active;if(body.check_interval_minutes!==undefined){const n=Number(body.check_interval_minutes);if(!allowedIntervals.has(n))return json({error:'Invalid check interval'},400);const a=await account(ctx);if(a.plan==='free'&&n<1440)return json({error:'Free monitors can run daily or weekly. Upgrade for faster checks.'},402);patch.check_interval_minutes=n}if(body.webhook_url!==undefined){const w=String(body.webhook_url||'').trim();if(w)safe(w);patch.webhook_url=w||null}if(typeof body.webhook_enabled==='boolean')patch.webhook_enabled=body.webhook_enabled;if(body.notes!==undefined)patch.notes=String(body.notes||'').slice(0,2000).trim()||null;return json(await upd('monitors',`id=eq.${encodeURIComponent(m.id)}`,patch)||{ok:true})}
if(body.action==='review_change'){if(!body.change_id)return json({error:'Missing change id'},400);const c=(await sel(`changes?id=eq.${encodeURIComponent(String(body.change_id))}&select=monitor_id&limit=1`))[0];if(!c||!await ownedMonitor(ctx,c.monitor_id))return json({error:'Change not found'},404);return json(await upd('changes',`id=eq.${encodeURIComponent(String(body.change_id))}`,{reviewed_at:body.reviewed===false?null:new Date().toISOString(),review_note:body.note?String(body.note).slice(0,500):null})||{ok:true})}
if(body.action==='history'){if(!body.id||!await ownedMonitor(ctx,String(body.id)))return json({error:'Monitor not found'},404);const id=encodeURIComponent(String(body.id));return json({snapshots:await sel(`snapshots?monitor_id=eq.${id}&select=id,page_title,content_hash,created_at&order=created_at.desc&limit=100`),changes:await sel(`changes?monitor_id=eq.${id}&select=*&order=created_at.desc&limit=100`)})}
if(body.action==='test_webhook'){const m=body.id?await ownedMonitor(ctx,String(body.id)):null;if(!m?.webhook_url)return json({error:'Webhook URL not configured'},400);return json(await sendWebhook(m,null,'PlanSentry test',true))}
if(body.action==='export'){const m=await sel(`monitors?${ownerQ(ctx)}&select=*&order=created_at.desc`),ids=m.map((x:any)=>x.id);let ch:any[]=[];if(ids.length){const ors=ids.map((id:string)=>`monitor_id.eq.${id}`).join(',');ch=await sel(`changes?or=(${ors})&select=*&order=created_at.desc&limit=5000`)}return json({exported_at:new Date().toISOString(),monitors:m,changes:ch})}
if(body.action==='delete'){const m=body.id?await ownedMonitor(ctx,String(body.id)):null;if(!m)return json({error:'Monitor not found'},404);await del('monitors',`id=eq.${encodeURIComponent(m.id)}`);return json({ok:true})}
return json({error:'Unknown action'},400)}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});
